//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> BillID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
    }
}
