//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string FDA { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Ingredient { get; set; }
        public string ImageURL { get; set; }
        public string Detail { get; set; }
        public string Barcode { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
