//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public Nullable<int> CateID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Buy { get; set; }
        public string Size { get; set; }
        public string Code { get; set; }
        public string Ingredients { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Sale { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
